### ISSUE TITLE
the difference of spr loss coefficient in the paper and the code

### ISSUE THREAD

**Issue by yilin-wu98** [mila-iqia/spr#21]
Dear @ankeshanand

I am trying to use your code to reproduce the result in your paper *Data-Efficient Reinforcement Learning with
Self-Predictive Representations*. I am a little confused about one of the hyperparameters used in your code. 

In the run.py,  the model-spr-weight is set to 5. and the running command doesn't change this hyperparameter so I think the lambda coefficient of spr loss is 5. in the code. However, in the appendix of the paper on the arxiv, the listed hyperparameter of spr loss coefficient is 2. Therefore, I am wondering which one is correct. Do I misunderstand some part of the code?

**Comment by MaxASchwarzer** [comment]
Hi Yilin,

The way the code calculates the SPR loss is slightly different from how it's written up in the paper, so we adjust the loss weight in the code to compensate.  You can convert between the two by code_weight = paper_weight * K/2, where K is the prediction depth used.

Best,
Max

**Comment by geekyutao** [comment]
> Hi Yilin,
> 
> The way the code calculates the SPR loss is slightly different from how it's written up in the paper, so we adjust the loss weight in the code to compensate. You can convert between the two by code_weight = paper_weight * K/2, where K is the prediction depth used.
> 
> Best,
> Max

Hi Max,
    So the weight should be set to 10 if K is 10? Pls correct me if I'm wrong. Thanks!

**Comment by MaxASchwarzer** [comment]
That would match the paper's notation, but I suspect that you would get better results by using a lower weight like 5 in that case.  Hard to say for sure without trying it, though.
