### ISSUE TITLE
use GpuResetCollector instead of CpuResetCollector

### ISSUE THREAD

**Issue by noahcao** [mila-iqia/spr#22]
Thanks for the great work.

In your implementation, you define the class SerialSampler based on CpuResetCollector:

> 
    class SerialSampler(BaseSampler):
    """The simplest sampler; no parallelism, everything occurs in same, master
    Python process.  This can be easier for debugging (e.g. can use
    ``breakpoint()`` in master process) and might be fast enough for
    experiment purposes.  Should be used with collectors which generate the
    agent's actions internally, i.e. CPU-based collectors but not GPU-based
    ones.
    NOTE: We modify this class from rlpyt to pass an id to EnvCls when creating
    environments.
    """
  
    def __init__(self, *args, CollectorCls=CpuResetCollector,
            eval_CollectorCls=SerialEvalCollector, **kwargs):
        super().__init__(*args, CollectorCls=CollectorCls,
            eval_CollectorCls=eval_CollectorCls, **kwargs)

It seems to cause high workload on CPU. I thus wonder how we should migrate the GpuResetCollector. I tried simply replacing **CpuResetCollector** with **GpuResetCollector**, but it caused some error:

>  File "/home/jinkun/git/spr-disentangled/src/rlpyt_utils.py", line 406, in obtain_samples
  self.agent_inputs, self.traj_infos, it)
 File "/home/jinkun/git/spr/src/rlpyt/rlpyt/samplers/parallel/gpu/collectors.py", line 20, in collect_batch
act_ready, obs_ready = self.sync.act_ready, self.sync.obs_ready
AttributeError: 'NoneType' object has no attribute 'act_ready'

**Comment by ankeshanand** [comment]
We sample batch sizes of 1 during acting, so we don't need a GPU for inference.
