### ISSUE TITLE
Conv2D?

### ISSUE THREAD

**Issue by slerman12** [mila-iqia/spr#25]
I noticed the model uses a Conv2D network. Doesn't this fail to account for time? A game like Pong requires at least 2 frames to know the trajectory of the ball.

**Comment by MaxASchwarzer** [comment]
We're stacking the four most recent frames together along the channel dimension, so the conv2d is able to take changes over time into account.   In principle you could use a three-dimensional convolution, but given that we're only using four frames of history it would really be overkill.

If we did want to condition on the distant past the most promising method would probably be a recurrent architecture, like in https://openreview.net/pdf?id=r1lyTjAqYX.  It's just more complicated to work with, though, and it's not clear that you benefit much from it outside of the huge-data regime.
