### ISSUE TITLE
About the number of CPUs

### ISSUE THREAD

**Issue by yueyang130** [mila-iqia/spr#29]
Thanks for your reply in previous issue! I mistakely put EfficientZero results here (I fixed it now). 

There is still a question that confuses me. How many CPUs should one single run take?

(Since you closed previous issue, I open a new one.)

**Comment by MaxASchwarzer** [comment]
We used 8-10 CPUs, 30-40GB of RAM, and one GPU for each run. I imagine that performance might improve a little bit with more CPUs, but probably not dramatically.

**Comment by yueyang130** [comment]
Got it. I will conduct experiments by your instruction. Thanks a lot.
